version: '3.9'

services:
  db:
    image: 'maayanpeleg87/hotel-db:latest'
    restart: always
    container_name: 'hotel_db'
    ports:
      - '3306:3306'
  api:
    image: 'maayanpeleg87/hotel-api:latest'
    restart: always
    container_name: 'hotel_api'
    ports:
      - '8080:8080'
    depends_on:
      - db
  frontend: 
    image: 'maayanpeleg87/hotel-frontend:latest'
    restart: always
    container_name: 'hotel_frontend'
    ports:
      - '80:5000'
    depends_on:
      - api

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'
    volumes:
      - ./volumes/loki:/loki
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./volumes/loki/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    depends_on:
      - loki
  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    ports:
      - '3000:3000' 
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./loki/grafana/provisioning/:/etc/grafana/provisioning/